NewBet/NewBet/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as av


from betapp.views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', CompetitionsView.as_view(), name="competitions"),
    url(r'^competition/(?P<id>[\d]+)', CompetitionView.as_view(),
        name="competition"),
    url(r'^finished_fixtures/(?P<id>[\d]+)', FinishedFixturesView.as_view(),
        name="finished-fixtures"),
    url(r'^competition_table/(?P<id>[\d]+)', CompetitionTableView.as_view(),
        name="competition-table"),
    url(r'^login/', av.LoginView.as_view(
        template_name="register/login_form.html"), name="login"),
    url(r'^logout/', av.LogoutView.as_view(next_page="/"), name="logout"),
    url(r'^register/', RegisterView.as_view(), name="register"),
    url(r'^bet_fixture/(?P<id>[\d]+)', BetFixtureView.as_view(),
        name="bet-fixture"),
    url(r'^account_details/', AccountDetailsView.as_view(),
        name="account-details"),
    url(r'^show_team/(?P<team_id>[\d]+)', ShowTeamView.as_view(),
        name="show-team"),
    url(r'^add_competitions/(?P<season>[\d]+)', AddCompetitionsView.as_view(),
        name="add-competitions"),
    url(r'^team_standings/(?P<competition_id>[\d]+)/(?P<team_id>[\d]+)',
        TeamStandingsView.as_view(), name="team-standings"),
]

NewBet/betapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator


class Competition(models.Model):
    caption = models.CharField(max_length=128)
    league = models.CharField(max_length=12)
    number_of_matchdays = models.IntegerField()
    year = models.IntegerField()
    number_of_teams = models.IntegerField()
    current_matchday = models.IntegerField()
    api_id = models.IntegerField()

    def __str__(self):
        return self.caption


class Team(models.Model):
    name = models.CharField(max_length=256)
    crest_url = models.CharField(max_length=256, null=True, blank=True)
    squad_market_value = models.CharField(max_length=64, null=True, blank=True)
    code = models.CharField(max_length=12, null=True)
    short_name = models.CharField(max_length=64)
    competition = models.ForeignKey(Competition, null=True)

    def __str__(self):
        return self.name


STATUS_TAB = ((1, "SCHEDULED"),
              (2, "FINISHED"),
              (3, "PLAYING")
              )

BET_CHOICES = ((1, 1),
               (2, 2),
               (0, 0)
               )


class Fixture(models.Model):
    home_team = models.ForeignKey(Team, related_name='homeTeam')
    away_team = models.ForeignKey(Team, related_name='awayTeam')
    status = models.IntegerField(choices=STATUS_TAB, default=1)
    matchday = models.IntegerField()
    competition = models.ForeignKey(Competition, related_name='competition')
    date = models.DateTimeField()
    goals_home_team = models.IntegerField(default=None, null=True, blank=True)
    goals_away_team = models.IntegerField(default=None, null=True, blank =True)
    course_team_home_win = models.FloatField(default=1, blank=True)
    course_team_away_win = models.FloatField(default=1, blank=True)
    course_draw = models.FloatField(default=1, blank=True)
    fixture_result = models.IntegerField(default=-1, blank=True)

    def __str__(self):
        return str(self.home_team.name + " - " + self.away_team.name)


class AppUser(models.Model):
    # TODO: change cash to decimal
    cash = models.DecimalField(validators=[MinValueValidator(0.00)],
                               max_digits=6, decimal_places=2)
    bank_account_number = models.CharField(max_length=64)
    user = models.OneToOneField(User)

    def __str__(self):
        return self.user.username


class Bet(models.Model):

    BET_RESULTS = ((0, "LOST"),
                   (1, "WON"),
                   (2, "PENDING")
                   )

    bet_user = models.ForeignKey(AppUser, related_name="bet_user")
    bet_amount = models.DecimalField(validators=[MinValueValidator(0.01)],
                                     max_digits=6, decimal_places=2)
    fixture = models.ForeignKey(Fixture, related_name="fixture")
    bet = models.IntegerField(choices=BET_CHOICES)
    bet_course = models.FloatField(default=0)
    # bet result 0: LOST, 1: WIN
    bet_result = models.IntegerField(default=2, blank=True, choices=BET_RESULTS)

NewBet/betapp/forms.py
from django import forms
from django.forms import ModelForm

from .models import *


class LoginForm(forms.Form):
    username = forms.CharField(max_length=64)
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=64)
    email = forms.EmailField()
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)
    confirm_password = forms.CharField(max_length=32,
                                       widget=forms.PasswordInput
                                       )


class BetForm(ModelForm):
    class Meta:
        model = Bet
        fields = ['bet_amount', 'bet']

NewBet/betapp/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import PermissionRequiredMixin, \
    LoginRequiredMixin
from django.shortcuts import redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic.list import ListView
from django.conf import settings

from rest_framework.views import APIView
from rest_framework.response import Response

import redis

from .models import *
from .forms import *
from .api_connection import get_competitions, get_league_table
from .update_db import create_competition
from .tasks import bet_created


r = redis.StrictRedis(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB,
                      decode_responses=True)


class CompetitionsView(ListView):
    """
    Displays all competitions
    """
    model = Competition
    template_name = "competitions.html"


class CompetitionView(View):
    def get(self, request, id):
        """
        Displays competition and all fixtures in competition
        :param request: 
        :param id: int - competition id in db
        :return: rendered html with competition and fixtures
        """
        competition = Competition.objects.get(id=id)
        fixtures = Fixture.objects.filter(competition=competition,
                                          status=1,
                                          )
        context = {"competition": competition,
                   "fixtures": fixtures
                   }
        return render(request, 'fixtures.html', context)


class CompetitionTableView(View):
    def get(self, request, id):
        competition = Competition.objects.get(id=id)
        api_id = competition.api_id
        league_table = get_league_table(api_id)
        table = []
        for team in league_table['standing']:
            table.append({"position": team['position'],
                          "name": team['teamName'],
                          "games": team['playedGames'],
                          "wins": team['wins'],
                          "draws": team['draws'],
                          "losses": team['losses'],
                          "points": team['points'],
                          })
        context = {"table": table, "competition": competition}
        return render(request, 'league_table.html', context)


def get_bet_course(fixture, bet):
    """
    Gets bet course from fixture and returns it
    :param fixture: Fixture object
    :param bet: int - 1:home_win, 2:away_win, 0:draw
    :return: float - course
    """
    if bet == 1:
        return fixture.course_team_home_win
    elif bet == 0:
        return fixture.course_draw
    elif bet == 2:
        return fixture.course_team_away_win


class BetFixtureView(LoginRequiredMixin, View):
    redirect_field_name = "next"

    def get(self, request, id):
        """
        Displays form for betting 
        :param id: int - id of fixture
        :return: rendered form
        """
        fixture = Fixture.objects.get(id=id)
        if fixture.status == 1:
            form = BetForm
            context = {"fixture": fixture,
                       "form": form
                       }
            return render(request, "bet_form.html", context)

    def post(self, request, id):
        """
        Checks if form is valid, user has the cash, cash amount is valid and 
        then saves bet ot db
        :param id: int - fixture id
        :return: redirection to competitions view
        """
        fixture = Fixture.objects.get(id=id)
        user = request.user
        app_user = AppUser.objects.get(user=user)
        form = BetForm(request.POST)
        if form.is_valid():
            bet_amount = form.cleaned_data['bet_amount']
            bet = form.cleaned_data['bet']
            bet_course = get_bet_course(fixture, bet)
            # check if cash amount is valid
            if app_user.cash - bet_amount >= 0 and bet_amount >= 0.01:
                app_user.cash -= bet_amount
                app_user.save()
                bet = Bet.objects.create(bet_user=app_user,
                                         bet_amount=bet_amount,
                                         fixture=fixture,
                                         bet=bet,
                                         bet_course=bet_course
                                         )
                bet_created.delay(bet.id)
        return redirect(reverse_lazy('competitions'))


def check_if_exists(username):
    """
    Checks if user exists in db
    :param username: string
    :return: Not empty queryset if user in db else returns empty queryset
    """
    return User.objects.filter(username=username).exists()


class RegisterView(FormView):
    def test_func(self):
        return not self.request.user.is_authenticated

    template_name = "register_form.html"
    form_class = RegisterForm
    success_url = reverse_lazy('competitions')

    def form_valid(self, form):
        """
        Adds new AppUser to db
        :param form: form object
        :return: redirect to competitions view
        """
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        confirm_password = form.cleaned_data['confirm_password']

        messages = []
        flag = True

        if check_if_exists(username):
            messages.append("User already exists!!")
            flag = False
        if password != confirm_password:
            messages.append("Passwords dont match!!")
            flag = False

        if flag:
            user = User.objects.create_user(username=username,
                                            password=password,
                                            email=email
                                            )
            AppUser.objects.create(user=user,
                                   bank_account_number=111,
                                   cash=100
                                   )
        else:
            form = RegisterForm()
            context = {"messages": messages,
                       "form": form
                       }
            return render(self.request, "register_form.html", context)
        return super(RegisterView, self).form_valid(form)


class AccountDetailsView(LoginRequiredMixin, View):
    redirect_field_name = 'next'

    def get(self, request):
        """
        Displays AppUser's account details
        :return: html with account details
        """
        user = request.user
        app_user = AppUser.objects.get(user=user)
        bets = Bet.objects.filter(bet_user=app_user)
        context = {"user": user,
                   "app_user": app_user,
                   "bets": bets,
                   }
        return render(request, "my_account.html", context)


class TeamStandingsView(APIView):
    def get(self, request, competition_id, team_id):
        print(competition_id, team_id)
        list_name = "{}:{}:standing".format(competition_id, team_id)
        standings = r.hgetall(list_name)
        matchday_list = sorted([int(i) for i in standings.keys()])
        standing_list = [int(standings[str(mday)])for mday in matchday_list]
        data = {"matchday_list": matchday_list,
                "standing_list": standing_list
                }
        return Response(data)



class ShowTeamView(View):
    def get(self, request, team_id):
        """
        Displays Team object's details 
        :param team_id: int - id of Team object in db
        :return: html with team details
        """
        team = Team.objects.get(id=team_id)
        competition = team.competition
        team_fixtures_home = Fixture.objects.filter(home_team=team)
        team_fixtures_away = Fixture.objects.filter(away_team=team)

        all_fixtures = [game for game in team_fixtures_away] +\
                       [game for game in team_fixtures_home]

        played_fixtures = [game for game in all_fixtures if game.status == 2]
        scheduled_fixtures = [game for game in all_fixtures if game.status == 1]

        context = {"team": team,
                   "competition": competition,
                   "team_fixtures_home": team_fixtures_home,
                   "team_fixtures_away": team_fixtures_away,
                   "played_fixtures": played_fixtures,
                   "scheduled_fixtures": scheduled_fixtures
                   }

        return render(request, "show_team.html", context)


class AddCompetitionsView(PermissionRequiredMixin, View):
    permission_required = ['is_superuser']

    def get(self, request, season):
        """
        Displays all available teams for season and anables to select them 
        to be added to db. 
        Competitions can be added only by superuser!!!
        :param season: int - season start year
        :return: renders html with checkboxes for competition selection
        """
        competitions = get_competitions(season=season)

        context = {"competitions": competitions}
        return render(request, 'list_competitions.html', context)

    def post(self, request, season):
        """
        Adds selected competitions to db
        :param season: int - season start year
        :return: redirection to competitions view
        """
        selected_copmetitions = request.POST.getlist('competition')
        for competition_id in selected_copmetitions:
            create_competition(int(competition_id))
        return redirect(reverse_lazy('competitions'))


class FinishedFixturesView(View):
    def get(self, request, id):
        competition = Competition.objects.get(id=id)
        finished_fixtures = Fixture.objects.filter(competition=competition,
                                                 status=2)
        context = {"competition": competition,
                   "finished_fixtures": finished_fixtures

NewBet/betapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NewBet</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" href="{% static 'betapp/css/betapp.css' %}">

    {% block head %}{% endblock %}
</head>
<header class="page-header">
    <a href="{% url 'competitions' %}"><h1>NewBetApp</h1></a>
    <p>
        {% if user.username %}
        Logged user: {{ user.username }}<br>
        <a href="{{ action }}">{{ label }}</a><br>
        <a href="{% url 'account-details' %}">Account details</a>
        {% else %}
        <a href="{{ action }}">{{ label }}</a>
        {% endif %}
    </p>
</header>
<body>
<div class="content">
    {% block content %}{% endblock %}
</div>

</body>
</html>

NewBet/betapp/templates/bet_form.html
{% extends 'base.html' %}
{% block content %}

{% for message in messages %}
    <p>{{ message }}</p>
{% endfor %}
<div class="form">
    <h3>F I X T U R E</h3>
    <p>Sides: {{ fixture.home_team.name }} - {{ fixture.away_team.name }}</p>
    <p>
        Courses:<br>
        <strong>1X:</strong> {{ fixture.course_team_home_win }} |
        <strong>0X:</strong> {{ fixture.course_draw }} |
        <strong>2X:</strong> {{ fixture.course_team_away_win }}
    </p>
    <p>Date: {{ fixture.date }}</p>
    <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }}<br>
            {{ field }}<br>
        {% endfor %}
        <br>
        <input type="submit" value="Make bet">
    </form>
</div>
{% endblock %}

NewBet/betapp/templates/competitions.html
{% extends 'base.html' %}
{% block content %}
<h2>Competitons</h2>
<ul>
    {% for competition in competition_list %}
    <li><a href="{% url 'competition' competition.id %}">{{ competition.caption }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

NewBet/betapp/templates/finished_fixtures.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ competition.caption }}</h1>
{% include "links.html" %}
{% include "fixtures_filter.html" %}
{% include "list_fixtures.html" with fixtures=finished_fixtures %}
{% endblock %}

NewBet/betapp/templates/fixtures.html
{% extends 'base.html' %}
{% block head %}{% endblock %}
{% block content %}
<h1>{{ competition.caption }}</h1>
{% include "links.html" %}
{% include "fixtures_filter.html" %}

{% include "list_fixtures.html" with fixtures=fixtures %}
{% endblock %}

NewBet/betapp/templates/fixtures_filter.html
{% block head %}
{% load static %}
<script src="{% static 'betapp/js/fixtures-filter.js' %}"></script>
{% endblock %}
<div id="search">
    <label>Filter by matchday or team name:<br>
        <input type="text" id="match-filter">
    </label><br>
</div>

NewBet/betapp/templates/league_table.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ competition.caption }}</h1>
<table>
    <tr>
        <th>Position</th>
        <th>Team</th>
        <th>Games</th>
        <th>Wins</th>
        <th>Draws</th>
        <th>Losses</th>
        <th>Points</th>
    </tr>
    {% for team in table %}
    <tr>
        <td>{{ team.position }}</td>
        <td>{{ team.name }}</td>
        <td>{{ team.games }}</td>
        <td>{{ team.wins }}</td>
        <td>{{ team.draws }}</td>
        <td>{{ team.losses }}</td>
        <td>{{ team.points }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

NewBet/betapp/templates/links.html
<a href="{% url 'competition-table' competition.id %}">League Table</a><br>
<a href="{% url 'finished-fixtures' competition.id %}">Finished Fixtures</a><br>
<a href="{% url 'competitions' %}">Competitions</a>

NewBet/betapp/templates/list_competitions.html
{% extends 'base.html' %}
{% block content %}
<h1>Available competitions</h1>
<form method="POST" action="">
    {% csrf_token %}
    {% for comp in competitions %}
        <input type="checkbox" name="competition" value="{{ comp.id }}">
        {{ comp.caption }}<br>
    {% endfor %}
    <input type="submit" value="Add">
</form>

{% endblock %}

NewBet/betapp/templates/list_fixtures.html
{% block fixtures_list %}
<ul>
    {% for fixture in fixtures %}
    <div class="list">
        <li>{{fixture.date}} |
            <a href="{% url 'show-team' fixture.home_team.id %}">
                <span class="home-team-name">{{ fixture.home_team.name }}</span>
            </a> -
            <a href="{% url 'show-team' fixture.away_team.id %}">
                <span class="away-team-name">{{ fixture.away_team.name }}</span>
            </a> | matchday: <span class="matchday">{{ fixture.matchday }}</span>
            {% if  fixture.goals_home_team >= 0 %}
            RESULT: {{ fixture.goals_home_team }} : {{ fixture.goals_away_team }}
            {% endif %}
            <br>
            ODDS:
            <ol>
                <li> Home win: {{ fixture.course_team_home_win }}</li>
                <li> Draw: {{ fixture.course_draw }}</li>
                <li> Away win: {{ fixture.course_team_away_win }}</li>
            </ol>
            {% if fixture.status == 1 %}
                <a href="{% url 'bet-fixture' fixture.id %}">Bet fixture</a>
            {% endif %}
        </li>
    </div>
    {% endfor %}
</ul>
{% endblock %}

NewBet/betapp/templates/login_form.html
{% extends 'base.html' %}
{% block content %}
{% for message in messages %}
    <p>{{ message }}</p>
{% endfor %}
<div class="form">
    <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }}<br>
            {{ field }}<br>
        {% endfor %}
        <br>
        <input type="submit" value="Login">
    </form>
    <p>
        <strong>Not registered? <a href="{% url 'register' %}">Register now</a></strong>
    </p>
</div>
{% endblock %}

NewBet/betapp/templates/my_account.html
{% extends 'base.html' %}

{% block content %}

<p>Username: {{ user.username }}</p>
<p>Email {{ user.email }}</p>
<p>Cash: {{ app_user.cash }} PLN</p>

    <table border="2">
        <tr>
            <th>Fixture</th>
            <th>Result</th>
            <th>Bet</th>
            <th>Course</th>
            <th>Bet Amount</th>
            <th>Matchday</th>
            <th>Status</th>
            <th>Result</th>
        </tr>
        {% for bet in bets %}
        <tr>
            <td>{{ bet.fixture }}</td>
            <td>{{ bet.fixture.goals_home_team }} - {{ bet.fixture.goals_away_team }}</td>
            <td>{{bet.bet}}</td>
            <td>{{bet.bet_course}}</td>
            <td>{{ bet.bet_amount }} PLN</td>
            <td>{{ bet.fixture.matchday }}</td>
            <td>{{ bet.fixture.get_status_display }}</td>
            <td>{{ bet.get_bet_result_display }}</td>
        </tr>
        {% endfor %}
    </table>

<a href="{% url 'competitions' %}">Competitions</a>
{% endblock %}

NewBet/betapp/templates/show_team.html
{% extends 'base.html' %}
{% block head %}
{% load static %}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script src="{% static 'betapp/js/show-fixtures.js' %}"></script>
<script src="{% static 'betapp/js/plot-standings.js' %}"></script>
{% endblock %}
{% block content %}
<h1>{{ team.name }}</h1>
<h3>{{ competition.caption }}</h3>

{% include "links.html" %}
{% include "fixtures_filter.html" %}
<h3>League position</h3>
<div id="team-standings" data-competition-id="{{competition.id}}" data-team-id="{{team.id}}">
</div>
<br>
<a class="fixtures-description" href="">Team fixtures home</a>
<div>
    {% include "list_fixtures.html" with fixtures=team_fixtures_home %}
</div>
<br>
<a class="fixtures-description" href="">Team fixtures away</a>
<div>
    {% include "list_fixtures.html" with fixtures=team_fixtures_away %}
</div>
<br>
<a class="fixtures-description" href="">Played team fixtures</a>
<div>
    {% include "list_fixtures.html" with fixtures=played_fixtures %}
</div>
<br>
<a class="fixtures-description" href="">Scheduled team fixtures</a>
<div>
    {% include "list_fixtures.html" with fixtures=scheduled_fixtures %}
</div>
<br>
{% endblock %}